language: objective-c
rvm: 2.0.0
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - cd EnmlConverter && pod install
script: xctool -workspace EnmlConverter.xcworkspace -scheme EnmlConverter -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build